unitsOfMeasure = [
  "Unit of measure is unknown",
  "ampere (amp) [amp, ampere]",
  "boolean",
  "btu/h [btuh]",
  "celsius (C) [C, celsius]",
  "centimeter (cm) [cm]",
  "cubic feet",
  "cubic feet per minute (cfm)",
  "cubic meter",
  "day",
  "days",
  "Deadbolt status (See below)",
  "decibel (db) [db]",
  "decibel A (dbA) [dbA]",
  "degree",
  "Door lock alarm (See below)",
  "european macroseismic",
  "Fahrenheit (F) [F]",
  "feet",
  "hour",
  "hours",
  "absolute humidity",
  "relative humidity",
  "inches of mercury (inHg)",
  "inches/hour",
  "index",
  "kelvin (K) [K]",
  "keyword",
  "kilogram (kg) [kg]",
  "kilovolt (kV)",
  "kilowatt (kW)",
  "kilopascal (kPa) [kpa]",
  "kilometers/hour (KPH)",
  "kilowatts/hour (kWH) [kwh]",
  "liedu",
  "liter (l)",
  "lux [lux]",
  "mercalli",
  "meter (m)",
  "cubic meters/hour",
  "meters/sec (m/s)",
  "milliamp (mA)",
  "millisecond (ms)",
  "millivolt (mV)",
  "minute",
  "duration in minutes",
  "millimeters/hour (mm/hr)",
  "month (Jan=1, Feb=2, etc.)",
  "miles/hour (MPH)",
  "- Reserved -",
  "ohm [ohm]",
  "percent",
  "pound",
  "Power Factor",
  "Parts/Million (PPM)",
  "pulse count",
  "The raw value as reported by the device",
  "second",
  "Duration in seconds",
  "seimens/meter",
  "body wave magnitude scale",
  "Richter scale",
  "moment magnitude scale",
  "surface wave magnitude scale",
  "shindo",
  "SML",
  "Thermostat heat/cool state (See below)",
  "Thermostat mode (See below)",
  "Thermostat fan mode (See below)",
  "US gallon",
  "User number",
  "UV index",
  "volt [V, volt]",
  "watt [W, watt]",
  "watts/square meter",
  "weekday (Sun=0, Sat=1, etc.)",
  "Wind Direction in degrees (See below)",
  "year",
  "0-Off 100-On, 101-Unknown",
  "0-Open 100-Close, 101-Unknown",
  "Thermostat fan run state (See below)",
  "Thermostat fan mode override",
  "millimeter [mm]",
  "kilometer",
  "Secure Mode 0-Unlock 1-Lock",
  "Ohm Meter (Electrical resistivity)",
  "KiloOhm",
  "cubic meter/cubic meter",
  "Water activity",
  "rotations/Minute (RPM)",
  "Hertz (Hz)",
  "Angle Position degrees relative to North Pole",
  "Angle Position degrees relative to South Pole",
  "Power Management Alarm (See below)",
  "Appliance Alarm (See below)",
  "Home Health Alarm (See below)",
  "VOC Level (See below)",
  "Barrier Status (See below)",
  "Insteon Thermostat Mode (See below) - For Insteon compatibility, should use 67 (Thermostat Mode)",
  "Insteon Thermostat Fan Mode (See below) - For Insteon compatibility, should use 68 (Thermostat Fan Mode)",
  "A Level from 0-255 e.g. brightness of a dimmable lamp",
  "Degree multiplied by 2 (for Insteon compatibility) - For Insteon compatibility, should use 14 (degree)",
  "Kilowatt Second (kWs)",
  "Dollar",
  "Cents",
  "Inches",
  "Millimeters per day",
  "Raw 1-byte unsigned value",
  "Raw 2-byte unsigned value",
  "Raw 3-byte unsigned value",
  "Raw 4-byte unsigned value",
  "Raw 1-byte signed value",
  "Raw 2-byte signed value",
  "Raw 3-byte signed value",
  "Raw 4-byte signed value",
  "Most recent On style action taken for lamp control",
  "Mile",
  "Millibar (mb), typically used in barometric reports",
  "Hectopascal (hPa), typically used in barometric reports",
  "Watt Hour",
  "Inches per day"
]

temperatureUnitsOfMeasure = [
  unitsOfMeasure[17],
  unitsOfMeasure[26],
  unitsOfMeasure[4]
]

